### ISSUE TITLE
Sign Up API, email not recieved.

### ISSUE THREAD

**Issue by gogeta95** [fossasia/susi_server#11]
I used the sign up API and sent a sign up request, but did not get any verification email.
API was `/aaa/signup.json` .

**Comment by mariobehling** [comment]
@Orbiter Any updates?

**Comment by charany1** [comment]
@mariobehling , @Orbiter  , I just got the code set-up in eclipse , would like to work on this .

**Comment by mariobehling** [comment]
Please go ahead. Cheers.

**Comment by charany1** [comment]
@jig08 , my office's firewall blocks connection to smtp.gmail.com:587 , so I won't be able to handle this issue . Please de-assign .

**Comment by Orbiter** [comment]
This is fixed now. The reason that it was not working was a configuration name change in https://github.com/loklak/loklak_server/commit/2b4aa57473b720daed8ae0cd68d0d8186b469779#diff-3e9a75946a4fa527d7ad70015889fccbL52 which moved to susi_server. The fix was not done as code change but as configuration change on the server
