### ISSUE TITLE
Security Issues with Authentication

### ISSUE THREAD

**Issue by gogeta95** [fossasia/susi_server#12]
right now, the server is accepting user's passwords as query parameter and in plain text, which is a security flaw.
we need to implement HTTPS support as @Orbiter  already said.
and also we should send sensitive information like **username and passwords, in request body** and also apply Base64 encoding in password from client side, which, the server has to decode on receiving.
see [purpose of base 64 encoding](http://stackoverflow.com/questions/4070693/what-is-the-purpose-of-base-64-encoding-and-why-it-used-in-http-basic-authentica)

**Comment by jig08** [comment]
@gogeta95 would you like to take up this issue ?

**Comment by gogeta95** [comment]
sorry, I can't work on the server. I know only android right now.

**Comment by Orbiter** [comment]
This issue is full of misunderstandings. The cited stackoverflow page is not a solution recommendation, it is just a question. Base64 encoding is part of the http authentication stadard which is implemented in susi as defined by the standard.

Only https usage is required. I will put that ontop of susi. It is not a coding requirement.

The access to the server using POST is correct and functional.

There is nothing to do here on the coding part. Therefore nobodoy of you can work on it.

All you need is an address to connect to asksusi.com. During development time, that is a http address - unsafe, right. For production it will be a https address. Please make that configurable.
