### ISSUE TITLE
Fix userStats, skillsStats for admin

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_server#1376]
**Actual Behaviour**

Currently, no stats are given for:

1. User Registrations over Time
2. Skill creations over time
3. Skill Uses over Time

**Expected Behaviour**

Fix it

**Would you like to work on the issue?**

No

**Comment by Orbiter** [comment]
Working on issues like that is much easier if the API endpoints are given in the issue text.

I found:
1. http://localhost:4000/aaa/getUsers.json?getUserStats=true for field signupOverTime

**Comment by fragm3** [comment]
Oh, sorry.

For other two:
https://api.susi.ai/cms/getSkillList.json?access_token=zz

2. Skill creations over time: `creationOverTime`
3. Skill Uses over Time: `lastAccessOverTime`

**Comment by Orbiter** [comment]
The root cause for the missing registration time series is, that this information is not at all in the accounting object. The cause for that is, that the registration time is either written by signup without registration mail - or (I guess) when the registration mail arrived. Unfortunately, that last detail is not implemented, the registration time is then not written.

**Comment by Orbiter** [comment]
Wow. I fixed all these endpoints but now the stats are in the admin panel removed. Please check.

**Comment by fragm3** [comment]
@Orbiter wow, amazing thanks
