### ISSUE TITLE
Create installation instructions for setup on Google cloud with Kubernetes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#159]
How to setup SUSI.AI server with Kubernetes on Google Cloud?

Please add installation instructions into the docs/installation folder.

**Comment by betterclever** [comment]
@mariobehling The current merged implementation has some problems.
1. It is pulling from @jyoth1raditya 's docker and not building a image then and there and deploying it. (since main motive of kubernetes deployment is that every developer has his deployment from source code from their own fork for easy testing)
2. Info regarding updating deployment and scaling up should have also been provided.

I have set it up with correct method as was suggested by Google in their Kubernetes Codelab. I wish to make changes here.

**Comment by niranjan94** [comment]
@mariobehling @betterclever @jyoth1raditya @Orbiter 

Hi ... I just went through the kubernetes deployment steps/config here. But seems like everything is just running in one pod. This way we're not actually using the features and potential of kubernetes. The current setup is pretty similar to running on a single google compute or Amazon EC2 or VPS instance. This isn't scalable either. 

What we need is ideally a setup like this (which we use for the Open Event Project)
- A set of kubernetes configurations which make managing it very easy -https://github.com/fossasia/open-event-orga-server/tree/nextgen/kubernetes/yamls
- This also allows us to deploy with a simple command such as `kubectl create -R -f ./director-with-config`
- A proper guide - https://github.com/fossasia/open-event-orga-server/blob/nextgen/docs/installation/gce-kubernetes.md
- A set of official docker images to use. (Auto built) - https://hub.docker.com/u/eventyay/
- Running components of the server in different pods so each of them are individually scalable. (The database running a pod. The API Server running in a pod. Etc.)
