### ISSUE TITLE
Analysis of https://github.com/loklak/loklak_server/issues/547

### ISSUE THREAD

**Issue by Fluepke** [fossasia/susi_server#221]
For implementing the **wiki system** we need a fine grained **AAA** system (_authorisation_, _authentication_, _accounting_).

As this was an already an [issue](https://github.com/loklak/loklak_server/issues/547) within the loklak project, we need to figure out the current situation and the necessary changes.

### What is currently there?
* **json** file backed persistence layer (see `JsonTray.java`)
* Each servlet can define a `minimumBaseUserRole` by overriding `public BaseUserRole getMinimalBaseUserRole()`, however this functionality seems not to be working as stated in PR #207.
* Each `Servlet` can define the user's permissions by overriding `getDefaultPermissions`.

### What do we need and how can we achieve this?
* Concerning performance the `JsonTray`, which is acting as a persistence layer: It should be able to store the information inside a database. How about using an `Object Relational Mapper`? Then we wouldn't need to care about accessing the files, we would have a database abstraction (thus we could per default use a SQLlite database). Same goes for **skills** and all the other stuff. We need to consider that things scale up, when we're building the **Wikipedia for artificial intelligence**.
  * [loklak_server/362](https://github.com/loklak/loklak_server/issues/362) might require us to write **queries** (figuring out the users group, querying the group for permissions, etc.). This will become hard when working with json files.
* We might need more specific authorization mechanisms than the `BaseUserRole`. Here are my thoughts:
  * We could use the linux approach with `users` and `groups`. A user can be added to a group. A group may have access rights on a module and a user may as well.
  * We could add module specific authorization information (e.g. amount of queries, query size, calculation time, etc.) within the user's `authorization` information as suggested in the loklak [issue](https://github.com/loklak/loklak_server/issues/547)

**Comment by Orbiter** [comment]
About first point:
To be able to run susi with fail-over, i.e. within a kubernetes environment, we actually need a AAA database externally from susi. But we also need that database for other settings. We would need it for the Accounting data. We must try to find a common solution for all that common data storage. A nosql solution as Florian suggests may be appropriate.

Here we should start an assessment to choose the right storage system.

However, we should keep this in mind and replace the JsonTray later or within a concurrent development. This class gives us enough transparency about storage that we can just work on on the AAA system. It is not the situation that we must stop here, do the storage first and then continue. We can continue without the storage, but do that concurrently as well.

About the second point:
Yes lets go with the linux group model. It looks like most of the requirements of the issue is implemented.

**Comment by dynamitechetan** [comment]
@Fluepke  can you explain more why do we need groups?
