### ISSUE TITLE
Deploy development branch and master branch to Google Cloud with Kubernetes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#240]
Most developers have already deployed the l[SUSI.AI server to Google cloud](https://github.com/fossasia/susi_server/wiki). How can we now automate this process and automatically deploy SUSI.AI to the cloud.

There should be two deployments:
1. Deployment from development branch for testing.
2. Deployment from master branch for production.

Before we switch the SUSI.AI domain to the cloud deployment, please implement the flow and test it for several days.

@mayank408 @chiragw15 @amitiwary999 @AliAyub007 @Manveer695 @betterclever @chashmeetsingh @dynamitechetan @DravitLochan @jyoth1raditya @madhavrathi @saurabhjn76 @isuruAb @rishiraj824 @uday96

**Comment by uday96** [comment]
The orga server is deployed in the similar way. Checkout @niranjan94 comment here -https://github.com/fossasia/susi_server/issues/159#issuecomment-304507059 .

From what I have understood till now, 
- On every merge, we build and push a docker image to docker hub and update the kubernetes deployment. (Rolling update) - https://github.com/fossasia/open-event-orga-server/blob/nextgen/kubernetes/travis/deploy-nextgen.sh.
- Configure the main travis file to push kubernetes updates - https://github.com/fossasia/open-event-orga-server/blob/nextgen/.travis.yml#L34

**Comment by chiragw15** [comment]
#402 Auto deploys server (development branch) on Google Cloud Platform using Kubernetes and Docker. Here is the documentation for it https://github.com/fossasia/susi_server/blob/development/docs/installation/installation_kubernetes_gcloud.md . Here is the blog explaining the procedure http://blog.fossasia.org/auto-deployment-of-susi-server-using-kubernetes-on-google-cloud-platform/ . Now, after every PR merge in development branch, the deployment will automatically be updated . This is the link to development http://35.192.82.114/ 
Next steps: 
1. Clone susi_skill_data repo on server because we need it for skill_cms. For that a dummy user account is needed to continuously push the commits to skill_data_repo when they are edited on skill wiki. 
2. Shift to FOSSASIA GCP account.

**Comment by chiragw15** [comment]
Some discussions from gitter which will help.
>the susi_server takes the skills from susi_skill_data using the git repository which must currently be in parallel of the susi_server repository.
like: susi_server must be in git/susi_server and susi_skill_data must be in git/susi_skill_data
then susi_server finds the skills. There is currently no path definition for that. We can do that.
Because all skills must be passed from the wiki front-end to the susi_server api, the susi_server also writes into that repository and then makes a commit. That means we need a git user inside susi_server which does the commit. The changed data in susi_skill_data is then pushed to github like any other change that is done in a git repository.
I suggest to use a single special user for these commits and use a specific branch in susi_skill_data, like a ‚cms‘ branch.
The question in context with the kubernetes deployment is: can we have a file system for the susi_skill_data? Any git operations should then be done using a java client.


> an even awesome way would be https://kubernetes.io/docs/concepts/storage/volumes/#gitrepo
Then just update the revision hash on each push to the fossasia/susi_skill_data repo

>right now there is no development branch in susi_skill_data! For now we should just consider that the cms branch is also the production branch as the susi_server activates all changes right when they are edited. The cms branch should be there to know that changes inside that branch came from the cms. The question who may merge branches should be disconnected from the questions on how to implement git in susi_server to push the changes.

>right now a cron job pulls the master branch every minute into susi_skill_data on the susi_server. As long as the wiki is not active, that must be done to get updates. As soon as the wiki is active, this has to stop. The final situation should be, that no pushes should be done to the skil repository by hand. As long as updates are made manually in the git repository, conflicts must be fixed also manually.

**Comment by Orbiter** [comment]
susi_skill_data must be cloned to the docker root folder where susi_server is cloned.
According to https://github.com/fossasia/susi_server/issues/499 the susi_server will take care of updates of susi_skill_data

**Comment by abishekvashok** [comment]
@Orbiter @mariobehling is this solved?

**Comment by abishekvashok** [comment]
Hey, how could I unassign people if I don't have write access
![screenshot from 2017-12-10 10-02-15](https://user-images.githubusercontent.com/8947010/33801945-375c4218-dd91-11e7-8261-346c5252a208.png)

**Comment by abishekvashok** [comment]
@mariobehling can I work on this? i have deployed SUSI server to Google Cloud.
