### ISSUE TITLE
Change Susi apps to account and adopt new logic

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_server#25]
* [ ] Change api.asksusi.com to "Home" and use slug "/" instead of web URL
* [ ] Only show "Account Apps"
* [ ] Change top right menu "Apps" to "Account"
* [ ] Take out slug "/apps/". Instead of http://api.asksusi.com/apps/signup/ change to http://api.asksusi.com/signup/
* [ ] On apps page change background from black to white and take out effects (e.g. moving in of apps)
* [ ] Make accounting options (accounts apps) into a simple list of items (instead of app boxes)
* [x] Delete apps: 1) Boilerplate, 2) One-Click Deployment, 3) Web Scraper
* [ ] Take out left sidebar "Categories"

**Comment by KukkadapuSushma** [comment]
Hello, I would like to work on this issue!

**Comment by daminisatya** [comment]
@KukkadapuSushma you work now, any help you can follow up over here or on gitter

**Comment by KukkadapuSushma** [comment]
Sure, thanks @daminisatya

**Comment by samsruti** [comment]
@daminisatya I would like to work on this task.

**Comment by jig08** [comment]
@samsruti Sure, go ahead.

@KukkadapuSushma Any updates on this ?

**Comment by samsruti** [comment]
@mariobehling What are the 'Account Apps'? Do you mean to say that the Apps that user uploaded by himself/herself, i.e The personal apps?

**Comment by KukkadapuSushma** [comment]
@jig08 yes I have started working on it.

**Comment by samsruti** [comment]
@KukkadapuSushma what are the implementations you have done yet. So that I can start my work excluding those?

**Comment by daminisatya** [comment]
@samsruti May be let's divide the work! :) 
You take up the first four and @KukkadapuSushma will take up the last four. I guess she started with deleting the apps. 

Good to see the collaborative work :)

**Comment by samsruti** [comment]
@daminisatya I am stuck in here: Take out slug "/apps/". Instead of http://api.asksusi.com/apps/signup/ change to http://api.asksusi.com/signup/

This could be by shifting the apps into the /html/ directory. So I would like if you can assign this to someone better. Since I got the top 4 i could fixed only 2 :)
Here is the pull request:  https://github.com/fossasia/susi_server/pull/36

**Comment by KukkadapuSushma** [comment]
I am done with partially half of my tasks, would deploy to development once after i finish completely @daminisatya

**Comment by KukkadapuSushma** [comment]
Delete apps: 1) Boilerplate, 2) One-Click Deployment, 3) Web Scraper -- this task also makes "Demo" & "Peers API" on left navigation menu bar gets removed. Because "Demo" has -> "1)Boiler Plate and so other fields......  So, is that the way i have to remove them, or its fine?!?  @mariobehling

**Comment by KukkadapuSushma** [comment]
@daminisatya I am stuck in here: 6) Make accounting options (accounts apps) into a simple list of items (instead of app boxes)
and 
"Changing background of apps display area to WHITE"


 So I would like if you can assign this to someone better. Since I got the last 4 i could fix few:)
Here is the pull request: #38

**Comment by Abhi2424shek** [comment]
Updates guys

**Comment by KukkadapuSushma** [comment]
I am not sure whether i can still continue with this, someone else can take up further.

**Comment by mariobehling** [comment]
With the recent changes of SUSI we will update this approach in different issues. Closing this therefore.
