### ISSUE TITLE
Image action type

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/susi_server#264]
**Actual Behaviour**

Currently there is no image action type to return images. In bots image response I am applying checks like if (isURL and contains .jpg) then return image type message.

**Expected Behaviour**

There should be an image action type to return images.

**Screenshots of the issue**

![responseimage](https://user-images.githubusercontent.com/25840461/26891346-22923fea-4bce-11e7-9291-8e9ef4dbf3c7.PNG)

Here in type it should be image instead of answer

**Comment by Orbiter** [comment]
I already planned that susi shall have two actions regarding pictures:
- takeimage
- showimage

That looks like it is not related to your expected behaviour, but I believe it should be part of the same concept. The takeimage/showimage concept considers that you may be able to ask susi to *take an image* and then show it afterwards. So taking an image generates an asset storage identification which may be a file name of the client device. showing the image would refer to the same image. But if we do enough abstraction, showing would be able to show also remote stored images.

So lets distinguish image asset storage using a protocol name, like local images are referred with an file url:
file:///home/images/123.jpg
and remote images with just normal urls

So all concepts could be covered with just two attributes in the action:
```
{
  "type": "showimage",
  "url": <the url>
}
```

Would that be sufficient? or am I missing something?

**Comment by AliAyub007** [comment]
@Orbiter Yes this would be perfect and this is all I think as I would get the type by just parsing the json response from api and then do necessary actions for all bots.

**Comment by Orbiter** [comment]
The same idea is prepared as keywords for actions already: https://github.com/fossasia/susi_server/blob/development/src/ai/susi/mind/SusiAction.java#L51-L56

That means we should do the same for audio, video and images, both for showing and recording.
Having that in mind, please think about abstraction of these media when doing the implementation.

**Comment by AliAyub007** [comment]
If we consider all messenger where susi bots are working there is abstraction of these media types from their end and it will depend on type of response as soon as we get the response type from susi API then those types can be handled easily using messenger APIs that we are using with in bots.

**Comment by jyoth1raditya** [comment]
@Orbiter, I would like to work on image input for susi
