### ISSUE TITLE
Add Schema for Handling Groups in AAA

### ISSUE THREAD

**Issue by dynamitechetan** [fossasia/susi_server#289]
Currently, there is no schema for handling groups. 
I will add a JSON Schema and a set of blank files so that we can work on them collaboratively.

**Comment by Orbiter** [comment]
What is the purpose of groups? This is not a criticism to do that, in fact I believe that we do need the groups but how do we handle them in the context of authorization?

I believe a group should define which servlets can be accessed by a user which is otherwise not allowed to use the servlet. Therefore a group should have a list of servlets that are granted access.

Is that the concept with groups?

**Comment by dynamitechetan** [comment]
Oh. Okay. I thought like we can have user groups like Linux. 
For example create a group for admins and a separate groups for privileged users. 
Different groups of a privileged users can have different permissions and access rights. 
Something like that. But as you are suggesting,  we can also have groups for users which limits their access to some servlets.
