### ISSUE TITLE
analyse link is wrong

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_server#400]
**Actual Behaviour**

the "analyse" phrase brings up a text and a link where the skill can be edited. Like:

<img width="729" alt="analyse_fail" src="https://user-images.githubusercontent.com/238730/28463135-32d0b7ce-6e1f-11e7-8c4d-668e7342e73c.png">

But the link points to the wrong path. If I click on the link, I get

`https://github.com/fossasia/susi_server/blob/development/file:/languagetest`

**Expected Behaviour**

The correct link should be `https://github.com/fossasia/susi_skill_data/blob/master/models/general/assistants/en/language.txt`

**Comment by Orbiter** [comment]
The textual given link is also wrong!
This was working when the feature was implemented initially!

**Comment by saurabhjn76** [comment]
@Orbiter Can you please help me reproducing the bug, I am not able to get the same response from susi, when I try "meine sprache" or "my language". I got different replies and link for them was correct.
![image](https://user-images.githubusercontent.com/9781788/28466973-bf42effc-6e4b-11e7-86cd-4459b4045daf.png)
![image](https://user-images.githubusercontent.com/9781788/28466997-e03f6c76-6e4b-11e7-9b96-5a310e5893d8.png)
[https://github.com/fossasia/susi_skill_data/blob/master/models/general/assistants/en/language.txt](https://github.com/fossasia/susi_skill_data/blob/master/models/general/assistants/en/language.txt)
So I think everything is working fine, the bug which you got was probably because of the temporary dream file on etherpad.
I just made a dream and tested, and got this response
![image](https://user-images.githubusercontent.com/9781788/28467050-2c1d7e08-6e4c-11e7-91db-f6e474ccf25e.png)
When there is a temporary file in dream then the link gets wrong,I will put a condition and will change the link to etherpad.

**Comment by Orbiter** [comment]
Hm, well I guess you are right. Sorry for the confusion I caused. But you are right, that's also a good opportunity to react accordingly also for a Susi dream. Please make an addition.

**Comment by saurabhjn76** [comment]
@chiragw15 This can be closed too now.
