### ISSUE TITLE
History not consistent

### ISSUE THREAD

**Issue by uday96** [fossasia/susi_server#409]
**Actual Behaviour**

The history being fetched is not consistent and always return only 10 cognitions with `cognitions_remaning : 0` though new messages were entered.

url used : http://api.susi.ai/susi/memory.json?access_token=ACCESS_TOKEN

Initial History : https://pastebin.com/PwnqCu0X

Sent a query `twelve` using same access_token

New History : https://pastebin.com/uZH91cUv

We can see that the query `seven` is missing in new history.

Also the total cognitions returned is 10 where the first 5 messages are the latest 5 messages and the last 5 messages are the last 5 messages and all the messages in between are missing in history.

**Expected Behaviour**

Show proper history

**Steps to reproduce it**

1. Load initial history and ensure min 10 messages are present
2. Send a new query
3. Check history again. You will find missing messages in between in history.

**Comment by uday96** [comment]
@chiragw15 Please take a look

**Comment by chiragw15** [comment]
@uday96 I just checked and you are right. History is not consistent. This is because This line `List<SusiCognition> cognitions = DAO.susi.getMemories().getCognitions(client);` here https://github.com/fossasia/susi_server/blob/development/src/ai/susi/server/api/susi/UserService.java#L73 should theoretically give all previous user cognitions but somehow it gives only 5 latest ones. I tried this on localhost and instead of returning specific count of messages in history, I returned everything using this
```
String client = user.getIdentity().getClient();
List<SusiCognition> cognitions = DAO.susi.getMemories().getCognitions(client);
JSONArray coga = new JSONArray();
for (SusiCognition cognition : cognitions) {
      coga.put(cognition.getJSON());      
}
JSONObject json = new JSONObject(true);
json.put("cognitions", coga);
json.put("cognitions_count", cognitions.size());
return new ServiceResponse(json);
```
I had 12 previous cognitions in history but it returned only 5. So, there is a problem in retrieving messages from log files and not while returning them to user. Looking into it to see where it is wrong.

**Comment by Orbiter** [comment]
I can explain the behaviour: there is a number called 'awareness' which limits the number of conversation steps in the mind function to 5. That means the log forgets on purpose whats older. I understand that this is not useful for the memory servlet. I have to think about this.

**Comment by AakashMallik** [comment]
@Orbiter I was just working on an issue regarding history on the client side of SUSI and ended up backtracking it to the backend here. The concept of awareness is fine but we need to show the chat history to the user, right? So I think the awareness implementation should be left as it is but the history should be sent to the client without any intended loss in cognition messages. Can this bug be put to **high priority**?
