### ISSUE TITLE
getSkillMetadata endpoint is not working as expected

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_server#469]
**Actual Behaviour**

Currently, the endpoint is working only for some skills. Like
http://api.susi.ai/cms/getSkillMetadata.json?model=general&group=entertainment&language=en&skill=trivia_question
is showing the correct response. 
```
{
  "skill_metadata": {
    "model": "general",
    "group": "entertainment",
    "language": "en",
    "descriptions": "test your knowledge, susi will ask a question, let's check if you can answer it",
    "image": "images/trivia_question.png",
    "author": "saurabh jain",
    "author_url": "https://github.com/saurabhjn76",
    "skill_name": "trivia question",
    "dynamic_content": true,
    "examples": {"/susi_skill_data/models/general/entertainment/en/trivia_question.txt": [
      "question me",
      "ask me something"
    ]}
  },
  "accepted": true,
  "message": "Success: Fetched Skill's Metadata",
  "session": {"identity": {
    "type": "host",
    "name": "49.34.2.190",
    "anonymous": true
  }}
}
``` 
But is not working for skills like http://api.susi.ai/cms/getSkillMetadata.json?model=general&group=knowledge&language=en&skill=random_word 
Both the skills are updated as per new format.
I have tested it locally and everything runs fine. The endpoint is working as expected on the local server for all the skills.

![image](https://user-images.githubusercontent.com/9781788/29133989-e6c47940-7d52-11e7-8e90-f8dae1093956.png)

**Expected Behaviour**

It should work for all the skills

I tried but was not able to found the bug, since everything was running fine locally. 
@Orbiter @dynamitechetan @DravitLochan  Please help me to fix it up.

**Comment by dynamitechetan** [comment]
Okay. 
I think I found the reason why this endpoint is not working. 
This endpoint returns no meta data about the skill.
http://api.susi.ai/cms/getSkillMetadata.json?model=general&group=knowledge&language=en&skill=random_word
The reason is that this skill is not updated on the server mirror of the SUSI Skill Data repository yet.

Check this endpoint, it returns the skill data. It is not updated to the newer format. 
http://api.susi.ai/cms/getSkill.json?model=general&group=knowledge&language=en&skill=random_word 

I checked the susi_skill_repo, in that the random_word skill is updated to the latest skill format.
The reason might be a merge conflict that is occurring on the server copy of the skill_data_repo.
That's why it's not pulling the latest changes.

I will suggest @Orbiter to delete the server skill repo and clone it again from https://github.com/fossasia/susi_skill_data/

**Comment by Orbiter** [comment]
made a git reset and the repo should be updated now

**Comment by saurabhjn76** [comment]
Thanks, @Orbiter @dynamitechetan, now the work point is working as expected
