### ISSUE TITLE
Add a parameter of "skill type" in skill data for each skill

### ISSUE THREAD

**Issue by DNS-404** [fossasia/susi_server#815]
**Actual Behaviour**

Currently, all the skills are public.

**Expected Behaviour**

In order to allow user to create skills for his/her web bot, user has to create private skills. These skills will be applicable only to the chatbot of the user.

There would be two types of skills-
- `Public` skills
- `Private` skills

**Would you like to work on the issue?**

Yes.

**Comment by Orbiter** [comment]
We must clarify a bit what this will actually do. We may want features so that:
* a user can classify a skill as one which the user may edit alone.
* a user can create a skill without the need that this is published.

Both options could be named "private" but there is a collision in functionality. In fact, both options could be combined. I consider that this feature is about the the first option. That means that "private" would mean "no collaboration".

If we compare this on how github does the naming of repositories which are not open to the public we discover that actually the second option should have the name "private" repositories. Adding an attribute "private" to the skill itself does not fulfill this mission because the skills would still be published openly.

So there is the impression that the naming of the "private" attribute is not appropriate. We shoud rename it!

I suggest that we name these skills "protected". Because that is what the attribute will do: it will protect the skill from modifications by other users. It will not make the skill private.

**Comment by Orbiter** [comment]
I will add details on how to make the actual 'private' skills in https://github.com/fossasia/susi_server/issues/738

We can still use this feature here to protect skills within a collaboration environment from changes by other users.

**Comment by DNS-404** [comment]
Okay, understood. I'll do the changes. Thanks a lot.
